title: "Laura Harbach"
name: "Laura Harbach"
description: "Computational researcher working across astrophysics, migration modelling, and complex systems."
url: "https://lauraharbach.github.io"
baseurl: ""
repository: "lauraharbach/lauraharbach.github.io"
title_separator: "-"

locale: "en-GB"
permalink: /:title/
future: false
breadcrumbs: false
read_more: "disabled"
words_per_minute: 160
talkmap_link: false
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

author:
  name: "Laura Harbach"
  avatar: "profile.png"
  bio: "Computational researcher bridging astrophysics and humanitarian computer science."
  location: "London, UK"
  email: "laura.harbach@brunel.ac.uk"
  github: "lauraharbach"
  twitter: "LauraHarbach"
  orcid: "http://orcid.org/0000-0001-7944-0292"

include:
  - .htaccess
  - _pages
  - files

exclude:
  - CHANGELOG.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - SITE_STRUCTURE.md
  - talkmap.ipynb
  - talkmap.py
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .jekyll-cache
  - .sass-cache
  - _site
  - log
  - node_modules
  - tmp
  - vendor
  - package.json
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor

keep_files:
  - .git
  - .svn

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      path: "_pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: pages
    values:
      layout: "page"

plugins:
  - jekyll-sitemap
  - jekyll-feed

whitelist:
  - jekyll-sitemap
  - jekyll-feed

atom_feed:
  path:

google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:

twitter:
  username:

facebook:
  username:
  app_id:
  publisher:

og_image:

social:
  type: Person
  name: "Laura Harbach"
  links:
    - "https://github.com/lauraharbach"
    - "https://orcid.org/0000-0001-7944-0292"

analytics:
  provider: false

comments:
  provider:
